"""add tables

Revision ID: 6a8b3c983c59
Revises: 
Create Date: 2022-05-18 18:32:54.981737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8b3c983c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('dev_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('dev_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dev_id')
    )
    op.create_index(op.f('ix_devices_dev_id'), 'devices', ['dev_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.dev_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_id')
    )
    op.create_index(op.f('ix_endpoints_endpoint_id'), 'endpoints', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_endpoint_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_devices_dev_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
